{% set name = "pydantic-yaml" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_yaml-{{ version }}.tar.gz
  sha256: 09f6b9ec9d80550dd3a58596a6a0948a1830fae94b73329b95c2b9dbfc35ae00

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - importlib-metadata >=4.2.0
    - pip
  run:
    - python >={{ python_min }}
    - pydantic >=1.8
    - ruamel.yaml >=0.16.0,<0.18.0
    - importlib-metadata
    - typing-extensions >=4.5.0

test:
  imports:
    - pydantic_yaml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Adds some YAML functionality to the excellent `pydantic` library.
  home: https://github.com/NowanIlfideme/pydantic-yaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
