{% set name = "pydantic-yaml" %}
{% set version = "1.5.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_yaml-{{ version }}.tar.gz
  sha256: 8345ae97ad5861652df571486051a5b051d2abdfc8092ddb0e4e0383e5da9a12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - importlib-metadata >=4.2.0
    - pip
  run:
    - ruamel
    - typing_extensions >=4.5.0
    - python >={{ python_min }}
    - pydantic >=1.8
    - ruamel.yaml >=0.17.0,<0.19.0
    - importlib-metadata
    - typing-extensions >=4.5.0

test:
  imports:
    - pydantic_yaml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Adds some YAML functionality to the excellent `pydantic` library.
  home: https://github.com/NowanIlfideme/pydantic-yaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
