{% set name = "pydantic-yaml" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_yaml-{{ version }}.tar.gz
  sha256: 54bdaf4da25bca95bb9ba790b1a5c6b4b3e93f7cf218fcde46b3073b61779f81

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - setuptools-scm >=6.2
    - importlib-metadata >=4.2.0
    - pip
  run:
    - python >=3.7
    - pydantic >=1.8
    - ruamel.yaml >=0.16.0,<0.18.0
    - importlib-metadata
    - typing-extensions >=4.5.0

test:
  imports:
    - pydantic_yaml
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Adds some YAML functionality to the excellent `pydantic` library.
  home: https://github.com/NowanIlfideme/pydantic-yaml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
